# Generated by Django 3.2.9 on 2021-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('store_email', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=200)),
            ],
        ),
    ]
